In [1]:
import torch

from train_gan import CurrentDecoder, Critic, Generator, SignalEncoder

In [2]:
formfactor_encoder = SignalEncoder(signal_dims=240, latent_dims=10)
formfactor_encoder

SignalEncoder(
  (convnet): Sequential(
    (0): Conv1d(1, 8, kernel_size=(3,), stride=(2,), padding=(1,))
    (1): LeakyReLU(negative_slope=0.01)
    (2): Conv1d(8, 16, kernel_size=(3,), stride=(2,), padding=(1,))
    (3): LeakyReLU(negative_slope=0.01)
    (4): Conv1d(16, 32, kernel_size=(3,), stride=(2,), padding=(1,))
    (5): LeakyReLU(negative_slope=0.01)
  )
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (mlp): Sequential(
    (0): Linear(in_features=960, out_features=100, bias=True)
    (1): LeakyReLU(negative_slope=0.01)
    (2): Linear(in_features=100, out_features=50, bias=True)
    (3): LeakyReLU(negative_slope=0.01)
    (4): Linear(in_features=50, out_features=10, bias=True)
  )
)

In [3]:
formfactor = torch.rand(3, 240)
formfactor_encoder(formfactor)

tensor([[-0.0461,  0.0644,  0.0311, -0.0956, -0.1506, -0.0373, -0.0117,  0.0109,
          0.0791,  0.1494],
        [-0.0456,  0.0669,  0.0302, -0.0871, -0.1498, -0.0356, -0.0116,  0.0107,
          0.0826,  0.1520],
        [-0.0506,  0.0654,  0.0299, -0.0943, -0.1481, -0.0398, -0.0155,  0.0147,
          0.0818,  0.1490]], grad_fn=<AddmmBackward0>)

In [4]:
current_encoder = SignalEncoder(signal_dims=300, latent_dims=10)
current_encoder

SignalEncoder(
  (convnet): Sequential(
    (0): Conv1d(1, 8, kernel_size=(3,), stride=(2,), padding=(1,))
    (1): LeakyReLU(negative_slope=0.01)
    (2): Conv1d(8, 16, kernel_size=(3,), stride=(2,), padding=(1,))
    (3): LeakyReLU(negative_slope=0.01)
    (4): Conv1d(16, 32, kernel_size=(3,), stride=(2,), padding=(1,))
    (5): LeakyReLU(negative_slope=0.01)
  )
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (mlp): Sequential(
    (0): Linear(in_features=1216, out_features=100, bias=True)
    (1): LeakyReLU(negative_slope=0.01)
    (2): Linear(in_features=100, out_features=50, bias=True)
    (3): LeakyReLU(negative_slope=0.01)
    (4): Linear(in_features=50, out_features=10, bias=True)
  )
)

In [5]:
current_profile = torch.rand(3, 300)
current_encoder(current_profile)

tensor([[-0.0753, -0.0022,  0.1249,  0.0256,  0.0688, -0.0709, -0.0303, -0.0429,
          0.0759,  0.1181],
        [-0.0723,  0.0094,  0.1311,  0.0309,  0.0697, -0.0753, -0.0390, -0.0459,
          0.0764,  0.1212],
        [-0.0774,  0.0101,  0.1375,  0.0267,  0.0745, -0.0703, -0.0379, -0.0434,
          0.0782,  0.1219]], grad_fn=<AddmmBackward0>)

In [6]:
current_decoder = CurrentDecoder(latent_dims=10 + 5 + 1, current_dims=300)
current_decoder

CurrentDecoder(
  (mlp): Sequential(
    (0): Linear(in_features=16, out_features=50, bias=True)
    (1): LeakyReLU(negative_slope=0.01)
    (2): Linear(in_features=50, out_features=100, bias=True)
    (3): LeakyReLU(negative_slope=0.01)
    (4): Linear(in_features=100, out_features=1216, bias=True)
    (5): LeakyReLU(negative_slope=0.01)
  )
  (unflatten): Unflatten(dim=1, unflattened_size=(32, 38))
  (convnet): Sequential(
    (0): ConvTranspose1d(32, 16, kernel_size=(3,), stride=(2,), padding=(1,))
    (1): LeakyReLU(negative_slope=0.01)
    (2): ConvTranspose1d(16, 8, kernel_size=(3,), stride=(2,), padding=(1,), output_padding=(1,))
    (3): LeakyReLU(negative_slope=0.01)
    (4): ConvTranspose1d(8, 1, kernel_size=(3,), stride=(2,), padding=(1,), output_padding=(1,))
    (5): ReLU()
  )
)

In [7]:
latent = torch.rand(3, 10 + 5 + 1)
current_decoder(latent)

tensor([[0.0110, 0.0923, 0.0000, 0.0597, 0.0007, 0.0841, 0.0000, 0.0710, 0.0125,
         0.1143, 0.0000, 0.0613, 0.0155, 0.0876, 0.0000, 0.0639, 0.0075, 0.1002,
         0.0000, 0.0631, 0.0113, 0.1026, 0.0000, 0.0723, 0.0106, 0.1101, 0.0000,
         0.0681, 0.0000, 0.1010, 0.0000, 0.0878, 0.0098, 0.1057, 0.0000, 0.0621,
         0.0068, 0.0957, 0.0000, 0.0670, 0.0104, 0.1003, 0.0000, 0.0641, 0.0024,
         0.0873, 0.0000, 0.0720, 0.0128, 0.1043, 0.0000, 0.0598, 0.0069, 0.0933,
         0.0000, 0.0695, 0.0134, 0.1085, 0.0000, 0.0575, 0.0185, 0.0884, 0.0000,
         0.0692, 0.0092, 0.0934, 0.0000, 0.0721, 0.0000, 0.0859, 0.0000, 0.0654,
         0.0100, 0.0873, 0.0000, 0.0661, 0.0000, 0.0946, 0.0000, 0.0625, 0.0102,
         0.0961, 0.0000, 0.0718, 0.0000, 0.0849, 0.0000, 0.0676, 0.0071, 0.1116,
         0.0000, 0.0687, 0.0144, 0.1040, 0.0000, 0.0710, 0.0179, 0.1007, 0.0000,
         0.0666, 0.0000, 0.0909, 0.0000, 0.0595, 0.0161, 0.0972, 0.0000, 0.0664,
         0.0011, 0.0712, 0.0

In [8]:
# formfactor_decoder = CurrentDecoder(latent_dims=10 + 5 + 1, current_dims=240)
# formfactor_decoder

In [9]:
# latent = torch.rand(3, 10 + 5 + 1)
# formfactor_decoder(latent)

In [10]:
generator = Generator()
generator


Generator(
  (formfactor_encoder): SignalEncoder(
    (convnet): Sequential(
      (0): Conv1d(1, 8, kernel_size=(3,), stride=(2,), padding=(1,))
      (1): LeakyReLU(negative_slope=0.01)
      (2): Conv1d(8, 16, kernel_size=(3,), stride=(2,), padding=(1,))
      (3): LeakyReLU(negative_slope=0.01)
      (4): Conv1d(16, 32, kernel_size=(3,), stride=(2,), padding=(1,))
      (5): LeakyReLU(negative_slope=0.01)
    )
    (flatten): Flatten(start_dim=1, end_dim=-1)
    (mlp): Sequential(
      (0): Linear(in_features=960, out_features=100, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=100, out_features=50, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=50, out_features=10, bias=True)
    )
  )
  (current_decoder): CurrentDecoder(
    (mlp): Sequential(
      (0): Linear(in_features=16, out_features=50, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=50, out_features=100, bias=True)


In [11]:
formfactor = torch.rand(3, 240)
rf_settings = torch.rand(3, 5)
bunch_length = torch.rand(3, 1)

current_profile = generator(formfactor, rf_settings, bunch_length)
current_profile

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0

In [12]:
critic = Critic()
critic

Critic(
  (formfactor_encoder): SignalEncoder(
    (convnet): Sequential(
      (0): Conv1d(1, 8, kernel_size=(3,), stride=(2,), padding=(1,))
      (1): LeakyReLU(negative_slope=0.01)
      (2): Conv1d(8, 16, kernel_size=(3,), stride=(2,), padding=(1,))
      (3): LeakyReLU(negative_slope=0.01)
      (4): Conv1d(16, 32, kernel_size=(3,), stride=(2,), padding=(1,))
      (5): LeakyReLU(negative_slope=0.01)
    )
    (flatten): Flatten(start_dim=1, end_dim=-1)
    (mlp): Sequential(
      (0): Linear(in_features=960, out_features=100, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=100, out_features=50, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=50, out_features=10, bias=True)
    )
  )
  (current_encoder): SignalEncoder(
    (convnet): Sequential(
      (0): Conv1d(1, 8, kernel_size=(3,), stride=(2,), padding=(1,))
      (1): LeakyReLU(negative_slope=0.01)
      (2): Conv1d(8, 16, kernel_size=(3,), stride=(2,), 

In [13]:
critic(current_profile, formfactor, rf_settings, bunch_length)

tensor([[-0.1127],
        [-0.1282],
        [-0.1202]], grad_fn=<AddmmBackward0>)