In [1]:
import torch

from train_gan import Critic, Generator, SignalEncoder, SignalDecoder

In [2]:
formfactor_encoder = SignalEncoder(signal_dims=240, latent_dims=10)
formfactor_encoder

SignalEncoder(
  (convnet): Sequential(
    (0): Conv1d(1, 8, kernel_size=(3,), stride=(2,), padding=(1,))
    (1): LeakyReLU(negative_slope=0.01)
    (2): Conv1d(8, 16, kernel_size=(3,), stride=(2,), padding=(1,))
    (3): LeakyReLU(negative_slope=0.01)
    (4): Conv1d(16, 32, kernel_size=(3,), stride=(2,), padding=(1,))
    (5): LeakyReLU(negative_slope=0.01)
  )
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (mlp): Sequential(
    (0): Linear(in_features=960, out_features=100, bias=True)
    (1): LeakyReLU(negative_slope=0.01)
    (2): Linear(in_features=100, out_features=50, bias=True)
    (3): LeakyReLU(negative_slope=0.01)
    (4): Linear(in_features=50, out_features=10, bias=True)
  )
)

In [3]:
formfactor = torch.rand(3, 240)
formfactor_encoder(formfactor)

tensor([[ 0.0438, -0.0162, -0.1125, -0.0902,  0.0593, -0.0598,  0.0466, -0.1160,
         -0.0814, -0.0080],
        [ 0.0431, -0.0170, -0.1120, -0.0893,  0.0568, -0.0609,  0.0506, -0.1188,
         -0.0793, -0.0091],
        [ 0.0423, -0.0146, -0.1116, -0.0892,  0.0576, -0.0607,  0.0489, -0.1160,
         -0.0812, -0.0085]], grad_fn=<AddmmBackward0>)

In [4]:
current_encoder = SignalEncoder(signal_dims=300, latent_dims=10)
current_encoder

SignalEncoder(
  (convnet): Sequential(
    (0): Conv1d(1, 8, kernel_size=(3,), stride=(2,), padding=(1,))
    (1): LeakyReLU(negative_slope=0.01)
    (2): Conv1d(8, 16, kernel_size=(3,), stride=(2,), padding=(1,))
    (3): LeakyReLU(negative_slope=0.01)
    (4): Conv1d(16, 32, kernel_size=(3,), stride=(2,), padding=(1,))
    (5): LeakyReLU(negative_slope=0.01)
  )
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (mlp): Sequential(
    (0): Linear(in_features=1216, out_features=100, bias=True)
    (1): LeakyReLU(negative_slope=0.01)
    (2): Linear(in_features=100, out_features=50, bias=True)
    (3): LeakyReLU(negative_slope=0.01)
    (4): Linear(in_features=50, out_features=10, bias=True)
  )
)

In [7]:
current_profile = torch.rand(3, 300)
current_encoder(current_profile)

tensor([[-0.1769,  0.0814,  0.0207, -0.1438, -0.0163,  0.0421, -0.0626,  0.0496,
          0.0802,  0.0387],
        [-0.1768,  0.0788,  0.0212, -0.1429, -0.0156,  0.0420, -0.0661,  0.0483,
          0.0848,  0.0397],
        [-0.1780,  0.0818,  0.0193, -0.1457, -0.0157,  0.0389, -0.0666,  0.0471,
          0.0812,  0.0402]], grad_fn=<AddmmBackward0>)

In [8]:
current_decoder = SignalDecoder(latent_dims=10 + 5 + 1, signal_dims=300)
current_decoder

SignalDecoder(
  (mlp): Sequential(
    (0): Linear(in_features=16, out_features=50, bias=True)
    (1): LeakyReLU(negative_slope=0.01)
    (2): Linear(in_features=50, out_features=100, bias=True)
    (3): LeakyReLU(negative_slope=0.01)
    (4): Linear(in_features=100, out_features=1216, bias=True)
    (5): LeakyReLU(negative_slope=0.01)
  )
  (unflatten): Unflatten(dim=1, unflattened_size=(32, 38))
  (convnet): Sequential(
    (0): ConvTranspose1d(32, 16, kernel_size=(3,), stride=(2,), padding=(1,))
    (1): LeakyReLU(negative_slope=0.01)
    (2): ConvTranspose1d(16, 8, kernel_size=(3,), stride=(2,), padding=(1,), output_padding=(1,))
    (3): LeakyReLU(negative_slope=0.01)
    (4): ConvTranspose1d(8, 1, kernel_size=(3,), stride=(2,), padding=(1,), output_padding=(1,))
    (5): ReLU()
  )
)

In [10]:
latent = torch.rand(3, 10 + 5 + 1)
current_decoder(latent)

tensor([[0.6181, 0.7200, 0.5701, 0.6856, 0.6380, 0.6796, 0.5719, 0.6164, 0.5950,
         0.7326, 0.5750, 0.6969, 0.6455, 0.6632, 0.5605, 0.6532, 0.6091, 0.7390,
         0.5725, 0.6910, 0.6450, 0.6688, 0.5552, 0.6649, 0.6013, 0.7158, 0.5585,
         0.6978, 0.6255, 0.6911, 0.5582, 0.6709, 0.6231, 0.6895, 0.5507, 0.7095,
         0.6423, 0.6792, 0.5559, 0.6428, 0.5938, 0.7492, 0.5631, 0.6665, 0.6281,
         0.7093, 0.5511, 0.6761, 0.6138, 0.7166, 0.5672, 0.6921, 0.6301, 0.6792,
         0.5657, 0.6454, 0.6145, 0.7078, 0.5666, 0.6565, 0.6273, 0.6909, 0.5529,
         0.6874, 0.6128, 0.7289, 0.5507, 0.7128, 0.6840, 0.6351, 0.5413, 0.6672,
         0.6044, 0.7351, 0.5602, 0.6956, 0.6350, 0.6857, 0.5550, 0.6800, 0.6236,
         0.7051, 0.5607, 0.6751, 0.6210, 0.7095, 0.5529, 0.6743, 0.6171, 0.6959,
         0.5544, 0.6559, 0.6000, 0.7267, 0.5596, 0.6722, 0.6124, 0.7050, 0.5592,
         0.6468, 0.6173, 0.7018, 0.5510, 0.6854, 0.6104, 0.7333, 0.5733, 0.7068,
         0.6316, 0.6846, 0.5

In [11]:
formfactor_decoder = SignalDecoder(latent_dims=10 + 5 + 1, signal_dims=240)
formfactor_decoder

SignalDecoder(
  (mlp): Sequential(
    (0): Linear(in_features=16, out_features=50, bias=True)
    (1): LeakyReLU(negative_slope=0.01)
    (2): Linear(in_features=50, out_features=100, bias=True)
    (3): LeakyReLU(negative_slope=0.01)
    (4): Linear(in_features=100, out_features=960, bias=True)
    (5): LeakyReLU(negative_slope=0.01)
  )
  (unflatten): Unflatten(dim=1, unflattened_size=(32, 30))
  (convnet): Sequential(
    (0): ConvTranspose1d(32, 16, kernel_size=(3,), stride=(2,), padding=(1,), output_padding=(1,))
    (1): LeakyReLU(negative_slope=0.01)
    (2): ConvTranspose1d(16, 8, kernel_size=(3,), stride=(2,), padding=(1,), output_padding=(1,))
    (3): LeakyReLU(negative_slope=0.01)
    (4): ConvTranspose1d(8, 1, kernel_size=(3,), stride=(2,), padding=(1,), output_padding=(1,))
    (5): ReLU()
  )
)

In [14]:
latent = torch.rand(3, 10 + 5 + 1)
formfactor_decoder(latent)

tensor([[0.2512, 0.1607, 0.3342, 0.0848, 0.2348, 0.1481, 0.3468, 0.0869, 0.2471,
         0.1549, 0.3385, 0.0831, 0.2337, 0.1543, 0.3418, 0.0926, 0.2449, 0.1559,
         0.3568, 0.0771, 0.2459, 0.1656, 0.3543, 0.0957, 0.2607, 0.1558, 0.3337,
         0.0987, 0.2476, 0.1473, 0.3460, 0.0757, 0.2517, 0.1682, 0.3491, 0.0820,
         0.2268, 0.1459, 0.3407, 0.0923, 0.2608, 0.1700, 0.3373, 0.0978, 0.2413,
         0.1538, 0.3529, 0.0736, 0.2485, 0.1675, 0.3671, 0.0856, 0.2614, 0.1443,
         0.3354, 0.0832, 0.2509, 0.1609, 0.3479, 0.0882, 0.2424, 0.1474, 0.3425,
         0.0807, 0.2532, 0.1684, 0.3307, 0.0990, 0.2393, 0.1411, 0.3533, 0.0683,
         0.2482, 0.1656, 0.3477, 0.0942, 0.2213, 0.1480, 0.3376, 0.0825, 0.2530,
         0.1542, 0.3335, 0.0841, 0.2333, 0.1688, 0.3583, 0.0950, 0.2592, 0.1626,
         0.3366, 0.0984, 0.2548, 0.1478, 0.3353, 0.0886, 0.2482, 0.1569, 0.3366,
         0.1020, 0.2585, 0.1530, 0.3432, 0.0778, 0.2538, 0.1646, 0.3395, 0.0988,
         0.2401, 0.1406, 0.3

In [15]:
generator = Generator()
generator


Generator(
  (formfactor_encoder): SignalEncoder(
    (convnet): Sequential(
      (0): Conv1d(1, 8, kernel_size=(3,), stride=(2,), padding=(1,))
      (1): LeakyReLU(negative_slope=0.01)
      (2): Conv1d(8, 16, kernel_size=(3,), stride=(2,), padding=(1,))
      (3): LeakyReLU(negative_slope=0.01)
      (4): Conv1d(16, 32, kernel_size=(3,), stride=(2,), padding=(1,))
      (5): LeakyReLU(negative_slope=0.01)
    )
    (flatten): Flatten(start_dim=1, end_dim=-1)
    (mlp): Sequential(
      (0): Linear(in_features=960, out_features=100, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=100, out_features=50, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=50, out_features=10, bias=True)
    )
  )
  (current_decoder): SignalDecoder(
    (mlp): Sequential(
      (0): Linear(in_features=16, out_features=50, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=50, out_features=100, bias=True)
 

In [18]:
formfactor = torch.rand(3, 240)
rf_settings = torch.rand(3, 5)
bunch_length = torch.rand(3, 1)

current_profile = generator(formfactor, rf_settings, bunch_length)
current_profile

tensor([[0.4286, 0.4041, 0.4640, 0.4182, 0.4252, 0.3907, 0.4733, 0.4247, 0.4205,
         0.4137, 0.4620, 0.4118, 0.4276, 0.3913, 0.4752, 0.4194, 0.4279, 0.3908,
         0.4734, 0.4186, 0.4273, 0.3981, 0.4709, 0.4155, 0.4306, 0.4057, 0.4614,
         0.4034, 0.4317, 0.3921, 0.4684, 0.4106, 0.4309, 0.4040, 0.4646, 0.4002,
         0.4297, 0.3754, 0.4690, 0.4005, 0.4324, 0.3877, 0.4725, 0.3993, 0.4339,
         0.3889, 0.4709, 0.4117, 0.4280, 0.4076, 0.4720, 0.4189, 0.4254, 0.3840,
         0.4731, 0.4087, 0.4301, 0.4307, 0.4594, 0.4077, 0.4243, 0.3763, 0.4773,
         0.4168, 0.4295, 0.3970, 0.4637, 0.4156, 0.4219, 0.3945, 0.4728, 0.4141,
         0.4276, 0.4161, 0.4641, 0.4149, 0.4191, 0.3799, 0.4640, 0.4012, 0.4288,
         0.4071, 0.4642, 0.4177, 0.4281, 0.3855, 0.4727, 0.4219, 0.4260, 0.4167,
         0.4595, 0.4105, 0.4244, 0.3838, 0.4604, 0.4076, 0.4221, 0.4044, 0.4656,
         0.4051, 0.4301, 0.3910, 0.4753, 0.4159, 0.4258, 0.4116, 0.4628, 0.4013,
         0.4258, 0.3803, 0.4

In [19]:
critic = Critic()
critic

Critic(
  (formfactor_encoder): SignalEncoder(
    (convnet): Sequential(
      (0): Conv1d(1, 8, kernel_size=(3,), stride=(2,), padding=(1,))
      (1): LeakyReLU(negative_slope=0.01)
      (2): Conv1d(8, 16, kernel_size=(3,), stride=(2,), padding=(1,))
      (3): LeakyReLU(negative_slope=0.01)
      (4): Conv1d(16, 32, kernel_size=(3,), stride=(2,), padding=(1,))
      (5): LeakyReLU(negative_slope=0.01)
    )
    (flatten): Flatten(start_dim=1, end_dim=-1)
    (mlp): Sequential(
      (0): Linear(in_features=960, out_features=100, bias=True)
      (1): LeakyReLU(negative_slope=0.01)
      (2): Linear(in_features=100, out_features=50, bias=True)
      (3): LeakyReLU(negative_slope=0.01)
      (4): Linear(in_features=50, out_features=10, bias=True)
    )
  )
  (current_encoder): SignalEncoder(
    (convnet): Sequential(
      (0): Conv1d(1, 8, kernel_size=(3,), stride=(2,), padding=(1,))
      (1): LeakyReLU(negative_slope=0.01)
      (2): Conv1d(8, 16, kernel_size=(3,), stride=(2,), 

In [20]:
critic(current_profile, formfactor, rf_settings, bunch_length)

tensor([[-0.1022],
        [-0.1214],
        [-0.1093]], grad_fn=<AddmmBackward0>)